package pages.device;

import io.appium.java_client.AppiumDriver;
import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import static utils.Common.generateUniqueString;

public class PageSignUp extends PageBase {
    private AppiumDriver appiumDriver;
    private WebDriverWait wait;

    @FindBy(id = "txtEmail")
    WebElement email;

    @FindBy(id = "txtPassword")
    WebElement password;

    @FindBy(id = "txtConfirmPassword")
    WebElement confirmPassword;

    @FindBy(id = "txtDisplayName")
    WebElement displayName;

    @FindBy(id = "btnCreateAnAccount")
    WebElement btnCreateAccount;

    public PageSignUp (AppiumDriver appiumDriver){
        this.appiumDriver = appiumDriver;
        PageFactory.initElements(appiumDriver, this);
        super.closeTips(appiumDriver);
        this.wait = new WebDriverWait(appiumDriver, 25);
        this.email = this.wait.until(ExpectedConditions.presenceOfElementLocated(By.id("txtEmail")));
    }

    public void CreateAccount(String email, String password, String displayName){
        this.email.sendKeys(email);
        this.password.sendKeys(password);
        this.confirmPassword.sendKeys(password);
        this.displayName.sendKeys(displayName);
        this.btnCreateAccount.click();
        WebElement OkBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@text='OK']")));
        OkBtn.click();
    }

    public void CreateAccountWithAutoGeneratedEmail(String email, String password, String displayName){
        int index = email.indexOf("@");
        String generatedEmail = email.substring(0, index) + "_" + generateUniqueString() + email.substring(index, email.length());
        System.out.println("Create account with email: " + generatedEmail);
        this.email.sendKeys(generatedEmail);
        this.password.sendKeys(password);
        this.confirmPassword.sendKeys(password);
        this.displayName.sendKeys(displayName);
        this.btnCreateAccount.click();
        WebElement OkBtn = wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("//*[@text='OK']")));
        OkBtn.click();
    }
}
